version: '3.8'

services:
  postgres:
    container_name: store_db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: adminpassword123
      POSTGRES_DB: recycling_db
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: